#! /usr/bin/env python3
from PyQt5 import QtWidgets, uic

import sys, os, json
from pathlib import Path

# autogenerated by Qt Designer
# pyuic5 Wad/ Mod/ Loader.ui -o MainWindow.py'
from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(731, 377)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(10, 10, 711, 339))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.scriptLabel = QtWidgets.QLabel(self.gridLayoutWidget)
        self.scriptLabel.setObjectName("scriptLabel")
        self.gridLayout.addWidget(self.scriptLabel, 2, 3, 1, 1)
        self.browseLabel = QtWidgets.QLabel(self.gridLayoutWidget)
        self.browseLabel.setObjectName("browseLabel")
        self.gridLayout.addWidget(self.browseLabel, 2, 0, 1, 1)
        self.savedList = QtWidgets.QListWidget(self.gridLayoutWidget)
        self.savedList.setObjectName("savedList")
        self.gridLayout.addWidget(self.savedList, 3, 4, 7, 1)
        self.runButton = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.runButton.setObjectName("runButton")
        self.gridLayout.addWidget(self.runButton, 10, 0, 1, 5)
        self.scriptName = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.scriptName.setObjectName("scriptName")
        self.gridLayout.addWidget(self.scriptName, 3, 3, 1, 1)
        self.iWadSel5 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.iWadSel5.setAcceptDrops(True)
        self.iWadSel5.setObjectName("iWadSel5")
        self.gridLayout.addWidget(self.iWadSel5, 8, 0, 1, 1)
        self.iWadSel2 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.iWadSel2.setAcceptDrops(True)
        self.iWadSel2.setObjectName("iWadSel2")
        self.gridLayout.addWidget(self.iWadSel2, 5, 0, 1, 1)
        self.iWadSel0 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.iWadSel0.setAcceptDrops(True)
        self.iWadSel0.setObjectName("iWadSel0")
        self.gridLayout.addWidget(self.iWadSel0, 3, 0, 1, 1)
        self.iWadSel4 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.iWadSel4.setAcceptDrops(True)
        self.iWadSel4.setObjectName("iWadSel4")
        self.gridLayout.addWidget(self.iWadSel4, 7, 0, 1, 1)
        self.iWadSel3 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.iWadSel3.setAcceptDrops(True)
        self.iWadSel3.setObjectName("iWadSel3")
        self.gridLayout.addWidget(self.iWadSel3, 6, 0, 1, 1)
        self.iWadSel1 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.iWadSel1.setAcceptDrops(True)
        self.iWadSel1.setObjectName("iWadSel1")
        self.gridLayout.addWidget(self.iWadSel1, 4, 0, 1, 1)
        self.iWadText0 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.iWadText0.setObjectName("iWadText0")
        self.gridLayout.addWidget(self.iWadText0, 3, 1, 1, 1)
        self.iWadText1 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.iWadText1.setObjectName("iWadText1")
        self.gridLayout.addWidget(self.iWadText1, 4, 1, 1, 1)
        self.iWadText2 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.iWadText2.setObjectName("iWadText2")
        self.gridLayout.addWidget(self.iWadText2, 5, 1, 1, 1)
        self.iWadText3 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.iWadText3.setObjectName("iWadText3")
        self.gridLayout.addWidget(self.iWadText3, 6, 1, 1, 1)
        self.iWadText4 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.iWadText4.setObjectName("iWadText4")
        self.gridLayout.addWidget(self.iWadText4, 7, 1, 1, 1)
        self.iWadText5 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.iWadText5.setObjectName("iWadText5")
        self.gridLayout.addWidget(self.iWadText5, 8, 1, 1, 1)
        self.saveButton = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.saveButton.setObjectName("saveButton")
        self.gridLayout.addWidget(self.saveButton, 4, 3, 1, 1)
        self.savedLabel = QtWidgets.QLabel(self.gridLayoutWidget)
        self.savedLabel.setObjectName("savedLabel")
        self.gridLayout.addWidget(self.savedLabel, 2, 4, 1, 1)
        self.slottedLabel = QtWidgets.QLabel(self.gridLayoutWidget)
        self.slottedLabel.setObjectName("slottedLabel")
        self.gridLayout.addWidget(self.slottedLabel, 2, 1, 1, 1)
        self.line02 = QtWidgets.QFrame(self.gridLayoutWidget)
        self.line02.setFrameShape(QtWidgets.QFrame.VLine)
        self.line02.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line02.setObjectName("line02")
        self.gridLayout.addWidget(self.line02, 2, 2, 8, 1)
        self.line01 = QtWidgets.QFrame(self.gridLayoutWidget)
        self.line01.setFrameShape(QtWidgets.QFrame.HLine)
        self.line01.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line01.setObjectName("line01")
        self.gridLayout.addWidget(self.line01, 1, 0, 1, 5)
        self.poweredBy = QtWidgets.QLabel(self.gridLayoutWidget)
        self.poweredBy.setObjectName("poweredBy")
        self.gridLayout.addWidget(self.poweredBy, 0, 0, 1, 4)
        self.iWadText6 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.iWadText6.setObjectName("iWadText6")
        self.gridLayout.addWidget(self.iWadText6, 9, 1, 1, 1)
        self.iWadSel6 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.iWadSel6.setAcceptDrops(True)
        self.iWadSel6.setObjectName("iWadSel6")
        self.gridLayout.addWidget(self.iWadSel6, 9, 0, 1, 1)
        self.loadButton = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.loadButton.setObjectName("loadButton")
        self.gridLayout.addWidget(self.loadButton, 8, 3, 1, 1)
        self.delButton = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.delButton.setObjectName("delButton")
        self.gridLayout.addWidget(self.delButton, 6, 3, 1, 1)
        self.writtenBy = QtWidgets.QLabel(self.gridLayoutWidget)
        self.writtenBy.setObjectName("writtenBy")
        self.gridLayout.addWidget(self.writtenBy, 0, 4, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Mod Wad Loader"))
        self.scriptLabel.setText(_translate("MainWindow", "Mod Script Name"))
        self.browseLabel.setText(_translate("MainWindow", "Browse for WADs"))
        self.savedList.setSortingEnabled(True)
        self.runButton.setText(_translate("MainWindow", "Run!"))
        self.scriptName.setText(_translate("MainWindow", "my-script-name"))
        self.iWadSel5.setText(_translate("MainWindow", "IWAD Slot 5"))
        self.iWadSel2.setText(_translate("MainWindow", " IWAD Slot 2"))
        self.iWadSel0.setText(_translate("MainWindow", "IWAD Slot 0"))
        self.iWadSel4.setText(_translate("MainWindow", "IWAD Slot 4"))
        self.iWadSel3.setText(_translate("MainWindow", "IWAD Slot 3"))
        self.iWadSel1.setText(_translate("MainWindow", "IWAD Slot 1"))
        self.iWadText0.setText(_translate("MainWindow", "No IWAD Slotted"))
        self.iWadText1.setText(_translate("MainWindow", "No IWAD Slotted"))
        self.iWadText2.setText(_translate("MainWindow", "No IWAD Slotted"))
        self.iWadText3.setText(_translate("MainWindow", "No IWAD Slotted"))
        self.iWadText4.setText(_translate("MainWindow", "No IWAD Slotted"))
        self.iWadText5.setText(_translate("MainWindow", "No IWAD Slotted"))
        self.saveButton.setText(_translate("MainWindow", "--- Save Mod Script -->"))
        self.savedLabel.setText(_translate("MainWindow", "Saved Mod Scripts"))
        self.slottedLabel.setText(_translate("MainWindow", "Slotted WADs"))
        self.poweredBy.setText(_translate("MainWindow", "Powered by: GZDoom and the Mod Community."))
        self.iWadText6.setText(_translate("MainWindow", "No IWAD Slotted"))
        self.iWadSel6.setText(_translate("MainWindow", "IWAD Slot 6"))
        self.loadButton.setText(_translate("MainWindow", "<-- Load Mod Script ---"))
        self.delButton.setText(_translate("MainWindow", "--> Delete Mod Script <--"))
        self.writtenBy.setText(_translate("MainWindow", "By: Grimm"))
# end of Qt Designer autogenerated code

class MainWindow(QtWidgets.QMainWindow, Ui_MainWindow):
    def __init__(self, *args, obj=None, **kwargs):
        super(MainWindow, self).__init__(*args, **kwargs)
        self.setupUi(self)
        # variables for building the mod script
        self.engine = '/Applications/GZDoom.app/Contents/MacOS/gzdoom'
        self.iwads = ['','','','','','','',]
        self.script = ''
        self.script_name = 'my-script-name'
        # setup JSON for saving scripts
        self.save_path = 'savedScripts.json'
        # {"Vannila Script": ["","","","","","",""]}
        self.script_collection = {}
        # ui hooks
        self.iWadSel0.clicked.connect(lambda: self.handle_file(self.iWadText0, 'iwad0'))
        self.iWadSel1.clicked.connect(lambda: self.handle_file(self.iWadText1, 'iwad1'))
        self.iWadSel2.clicked.connect(lambda: self.handle_file(self.iWadText2, 'iwad2'))
        self.iWadSel3.clicked.connect(lambda: self.handle_file(self.iWadText3, 'iwad3'))
        self.iWadSel4.clicked.connect(lambda: self.handle_file(self.iWadText4, 'iwad4'))
        self.iWadSel5.clicked.connect(lambda: self.handle_file(self.iWadText5, 'iwad5'))
        self.iWadSel6.clicked.connect(lambda: self.handle_file(self.iWadText5, 'iwad6'))
        self.saveButton.clicked.connect(self.save_script)
        self.delButton.clicked.connect(self.del_script)
        self.loadButton.clicked.connect(self.load_script)
        self.runButton.clicked.connect(self.run_script)
        self.read_scripts()
        return
    def handle_file(self, targetLabel, select_var):
        file, _ = QtWidgets.QFileDialog.getOpenFileNames(self)
        if file:
            file = str(file[0])
            targetLabel.setText(file.split('/')[-1])
            if select_var == 'iwad0':
                self.iwads[0] = file 
            elif select_var == 'iwad1':
                self.iwads[1] = file
            elif select_var == 'iwad2':
                self.iwads[2] = file
            elif select_var == 'iwad3':
                self.iwads[3] = file 
            elif select_var == 'iwad4':
                self.iwads[4] = file 
            elif select_var == 'iwad5':
                self.iwads[5] = file 
            elif select_var == 'iwad6':
                self.iwads[6] = file 
        else:
            targetLabel.setText('Error: Problem slotting IWAD.')
        return
    def build_script(self):
        # Reset script
        self.script = ''
        has_iwads = 0
        for iwad in self.iwads:
            if iwad != '':
                has_iwads += 1
        if has_iwads == 0:
            return self.engine
        self.script += self.engine + ' -iwad'
        for iwad in self.iwads:
            if iwad == '':
                continue
            else:
                self.script += ' "' + iwad + '"'
        self.script += ' -config ' + self.script_name.replace(" ", "-")
        return self.script
    def run_script(self):
        print(self.build_script())
        os.system(self.build_script())
        return
    def check_save_file(self):
        Path(self.save_path).touch()
        return
    def refresh_list(self):
        self.savedList.clear()
        for item in self.script_collection.keys():
            self.savedList.addItem(item)
    def read_scripts(self):
        self.check_save_file()
        with open(self.save_path, 'r') as f:
            self.script_collection = json.load(f)
        self.refresh_list()
        return
    def save_script(self):
        self.script_name = self.scriptName.text()
        if self.script_name == "Vanilla Script":
            return
        self.script_collection[self.script_name] = self.iwads
        self.check_save_file()
        with open(self.save_path, 'w') as f:
            json.dump(self.script_collection, f)
        self.refresh_list()
        return
    def del_script(self):
        selected = self.savedList.currentItem().text()
        if selected == "Vanilla Script":
            return
        self.script_collection.pop(selected)
        self.check_save_file()
        with open(self.save_path, 'w') as f:
            json.dump(self.script_collection, f)
        self.refresh_list()
        return
    def reset_iwad_text(self, label):
        if label.text() == "":
            label.setText("No IWAD Slotted")
        return
    def load_script(self):
        selected = self.savedList.currentItem().text()
        self.script_name = selected
        self.scriptName.setText(selected)
        self.iwads = self.script_collection[selected]
        self.iWadText0.setText(self.iwads[0].split('/')[-1])
        self.reset_iwad_text(self.iWadText0)
        self.iWadText1.setText(self.iwads[1].split('/')[-1])
        self.reset_iwad_text(self.iWadText1)
        self.iWadText2.setText(self.iwads[2].split('/')[-1])
        self.reset_iwad_text(self.iWadText2)
        self.iWadText3.setText(self.iwads[3].split('/')[-1])
        self.reset_iwad_text(self.iWadText3)
        self.iWadText4.setText(self.iwads[4].split('/')[-1])
        self.reset_iwad_text(self.iWadText4)
        self.iWadText5.setText(self.iwads[5].split('/')[-1])
        self.reset_iwad_text(self.iWadText5)
        self.iWadText6.setText(self.iwads[6].split('/')[-1])
        self.reset_iwad_text(self.iWadText6)
        return

if __name__ == '__main__':
    app = QtWidgets.QApplication(sys.argv)
    window = MainWindow()
    window.show()
    app.exec()